import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Reader for content/status.json — the build artifact behind /admin/status
 * (scripts/build-status.mjs: schedule.yaml joined with what the build actually
 * produced). Holds facts only: cluster ids, slugs, upstream URLs. Never a
 * base-path-prefixed href — the page applies NEXT_PUBLIC_BASE_PATH at render
 * time, same rule as generated MDX.
 *
 * `days`, and each day's `modules`, are in schedule.yaml's order — the order
 * the course is taught in.
 */

/** How a worksheet's deck reaches the reader. */
export type Deck =
  /** tex/<slug>/slides.tex compiled and hosted here (`pdf`/`tex` = staged). */
  | { kind: "built"; slug: string; pdf: boolean; tex: boolean }
  /** A prebuilt deck hosted elsewhere — linked out, never served by us. */
  | { kind: "external"; slug?: string; url: string }
  | { kind: "none"; slug?: string };

export type DayModule = {
  slug: string;
  title: string;
  cluster: string | null;
  unlisted: boolean;
  pdf: boolean;
  deck: Deck;
};

/** Where a day's buildable source is. `in-repo` is derived (the day has a
 *  worksheet); `never` means the day is marked `port: never` in schedule.yaml
 *  (deliberately not ported, so no source is awaited); the rest come from
 *  schedule.yaml's `source:` key. */
export type SourceKind = "in-repo" | "ready" | "partial" | "missing" | "never";

export type Day = {
  code: string;
  cluster: string;
  title: string;
  lead: string;
  doc: string;
  /** `kind` is the current truth: what schedule.yaml declared, or `in-repo`
   *  once the day has a worksheet. */
  source: { kind: SourceKind; url: string | null; note: string | null };
  slidesUrl: string | null;
  /** "never" = deliberately not ported (schedule.yaml `port: never`): no
   *  worksheet or deck is planned, and the page shows the day grey. */
  port: "never" | null;
  modules: DayModule[];
  live: boolean;
  slides: { kind: "built" | "external" | "none"; decks: Deck[] };
};

export type Status = {
  /** Generated by a --check run (watch / preview / pre-push): no PDFs were
   *  compiled, so the deck and PDF columns understate reality. */
  checkOnly: boolean;
  days: Day[];
  counts: {
    days: number;
    live: number;
    decksBuilt: number;
    decksHosted: number;
    awaitingSource: number;
    neverPort: number;
  };
};

const STATUS_FILE = path.join(process.cwd(), "content", "status.json");

/** null when the content build hasn't run yet (page renders a hint instead). */
export async function readStatus(): Promise<Status | null> {
  try {
    return JSON.parse(await readFile(STATUS_FILE, "utf8")) as Status;
  } catch {
    return null;
  }
}
